# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('difficulty', models.IntegerField(default=1)),
                ('steps', models.IntegerField(default=0)),
                ('jumps', models.IntegerField(default=0)),
                ('enemiesSpotted', models.IntegerField(default=0)),
                ('safeAreas', models.IntegerField(default=0)),
                ('encounters', models.IntegerField(default=0)),
                ('zones', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
            ],
        ),
    ]
