# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
