# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
        ('game', '0002_auto_20170227_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='currentZone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zone.Zone'),
        ),
    ]
