# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dmg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='heal',
            field=models.IntegerField(default=0),
        ),
    ]
