# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zombie', '0003_auto_20170222_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zombie.Player')),
                ('slot0', models.ManyToManyField(to='zombie.Item')),
            ],
        ),
    ]
