# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zombie', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='slot1',
            field=models.ManyToManyField(related_name='slot1', to='zombie.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='slot2',
            field=models.ManyToManyField(related_name='slot2', to='zombie.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='slot3',
            field=models.ManyToManyField(related_name='slot3', to='zombie.Item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='slot4',
            field=models.ManyToManyField(related_name='slot4', to='zombie.Item'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='zombie.Player'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='slot0',
            field=models.ManyToManyField(related_name='slot0', to='zombie.Item'),
        ),
    ]
