# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie', '0005_auto_20170222_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=100),
        ),
    ]
